http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "no-referrer"
        permissionsPolicy: "geolocation=(), microphone=(), camera=()"

        # Traefik v3 HSTS fields
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true

    compression:
      compress: {}
