http:
  routers:
    dockhand:
      rule: "Host(`dockhand.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: dockhand

    haos:
      rule: "Host(`haos.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares:
          - security-headers
          - haos-forwarded-headers
          - compression
      service: haos

    komga:
      rule: "Host(`komga.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: komga

    manyfold3d:
      rule: "Host(`manyfold3d.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: manyfold3d

    portainer:
      rule: "Host(`portainer.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: portainer

    portainer-2:
      rule: "Host(`portainer-2.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: portainer-2

    porttracker:
      rule: "Host(`porttracker.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: porttracker

    webmin-mid:
      rule: "Host(`webmin-mid.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: webmin-mid

    webmin-opti:
      rule: "Host(`webmin-opti.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: webmin-opti

    webmin-optiplex-two:
      rule: "Host(`webmin-optiplex-two.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: webmin-optiplex-two

    borg-optiplex-docker:
      rule: "Host(`borg-optiplex-docker.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: borg-optiplex-docker

    wud:
      rule: "Host(`wud.shome`)"
      entryPoints: ["websecure"]
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: wud

    k3s-catchall:
      rule: "HostRegexp(`{name:[a-z0-9-]+}.shome`)"
      entryPoints: ["websecure"]
      priority: 10
      tls:
        certResolver: stepca
      middlewares: ["security-headers", "compression"]
      service: k3s-traefik

