version: "3.9"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    networks:
      adguard_dhcp_net:
        ipv4_address: 192.168.200.202
    volumes:
      - /my/own/workdir:/opt/adguardhome/work
      - /my/own/confdir:/opt/adguardhome/conf
    environment:
      - TZ=America/New_York
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    # Healthcheck: no auth needed; treat 200 or 401 as "up"
    healthcheck:
      test: ["CMD-SHELL", "wget -S --spider -O /dev/null http://127.0.0.1:80/control/status 2>&1 | grep -Eq 'HTTP/[0-9.]+ (200|401)'"]
      start_period: 90s
      interval: 30s
      timeout: 5s
      retries: 10

networks:
  adguard_dhcp_net:
    driver: macvlan
    driver_opts:
      parent: enp1s0
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: 192.168.200.0/24
          gateway: 192.168.200.1
