#!/usr/bin/env bash

# This script prepares an app-consistent snapshot of relevant data for backup by Borg.
# Generated by borg-backup-survey.sh on 2026-08-01T22:16:08-04:00 for host: optiplex-two
# REVIEW BEFORE DEPLOYING - it reflects what was detected at survey time.
#
# It collects system information, Docker metadata, application data, database dumps,
# and platform state (Tailscale/Kubernetes where present). The resulting snapshot is
# staged in a temporary directory and atomically moved to the "latest" location for
# Borg to pick up. Run as root; backup data is protected with strict permissions (umask 077).
#
# Usage:
#   sudo ./borg-prep-appdata-optiplex-two.sh
# Deploy to /usr/local/sbin/borg-prep-appdata-optiplex-two.sh on optiplex-two and ensure Borg
# includes "${BASE}/latest" in its backup paths. Run before each Borg backup.
#
# Licensed under the MIT License. Provided "as is" without warranty.

set -Eeuo pipefail
umask 077

BASE="/var/backups/borg-apps"
LATEST="${BASE}/latest"

mkdir -p "$BASE"
TMP="$(mktemp -d "${BASE}/.tmp.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$TMP"/{metadata,docker,apps,databases,native,tailscale,kubernetes}

echo "Preparing app-consistent backup data for optiplex-two..."

# -----------------------------
# System and Docker inventory
# -----------------------------
{
  date -Is
  hostnamectl || true
  uname -a || true
  cat /etc/os-release || true
} > "$TMP/metadata/system-info.txt"

dpkg-query -W -f='${binary:Package}\t${Version}\n' > "$TMP/metadata/dpkg-packages.tsv" 2>/dev/null || true

docker ps -a --no-trunc > "$TMP/docker/docker-ps-a.txt" 2>/dev/null || true
docker images --digests > "$TMP/docker/docker-images.txt" 2>/dev/null || true
docker volume ls > "$TMP/docker/docker-volumes.txt" 2>/dev/null || true
docker network ls > "$TMP/docker/docker-networks.txt" 2>/dev/null || true

docker inspect $(docker ps -aq) > "$TMP/docker/docker-inspect-all.json" 2>/dev/null || true

# -----------------------------
# Compose project: statping
# -----------------------------
if [ -d /data/compose/14 ]; then
  rsync -a --delete \
    --exclude='*.db-wal' \
    --exclude='*.db-shm' \
    /data/compose/14/ "$TMP/apps/data-compose-14/"
fi

# -----------------------------
# Compose project: portainer
# -----------------------------
if [ -d /opt/docker/compose/portainer ]; then
  rsync -a --delete \
    --exclude='*.db-wal' \
    --exclude='*.db-shm' \
    /opt/docker/compose/portainer/ "$TMP/apps/opt-docker-compose-portainer/"
fi

# -----------------------------
# App data: /volume1/docker/portracker (76K)
# -----------------------------
if [ -d /volume1/docker/portracker ]; then
  rsync -a --delete \
    --exclude='*.db-wal' \
    --exclude='*.db-shm' \
    /volume1/docker/portracker/ "$TMP/apps/volume1-docker-portracker/"
fi

# -----------------------------
# Redis persistence flush: container searxng-valkey
# (dump.rdb itself is captured via the volume/bind backup)
# -----------------------------
if docker ps --format '{{.Names}}' | grep -qx 'searxng-valkey'; then
  docker exec 'searxng-valkey' redis-cli BGSAVE >/dev/null 2>&1 || true
  sleep 2
fi

# -----------------------------
# PostgreSQL dump: container postgres
# -----------------------------
if docker ps --format '{{.Names}}' | grep -qx 'postgres'; then
  docker exec 'postgres' pg_dumpall -U 'statup' \
    > "$TMP/databases/postgres-pg_dumpall.sql" 2>/dev/null \
    || echo "WARN: pg_dumpall failed for postgres"
fi

# SQLite-safe backup of /volume1/docker/portracker/portracker.db
if [ -f '/volume1/docker/portracker/portracker.db' ]; then
  sqlite3 '/volume1/docker/portracker/portracker.db' "PRAGMA wal_checkpoint(FULL);" >/dev/null 2>&1 || true
  sqlite3 '/volume1/docker/portracker/portracker.db' ".backup '$TMP/databases/volume1-docker-portracker-portracker.db.sqlite-backup'" || true
fi

# -----------------------------
# Tailscale state (node identity/keys - SECRET; do not restore to a second machine)
# -----------------------------
tailscale status > "$TMP/tailscale/status.txt" 2>/dev/null || true
if [ -d /var/lib/tailscale ]; then
  rsync -a --delete /var/lib/tailscale/ "$TMP/tailscale/state/"
fi

# -----------------------------
# Kubernetes (k3s): datastore snapshot + config
# -----------------------------
if command -v k3s >/dev/null 2>&1; then
  # etcd datastore: use the built-in snapshot; SQLite datastore: safe-copy the db.
  if [ -d /var/lib/rancher/k3s/server/db/etcd ]; then
    k3s etcd-snapshot save --dir "$TMP/kubernetes/etcd-snapshots" >/dev/null 2>&1 \
      || echo "WARN: k3s etcd-snapshot failed"
  elif [ -f /var/lib/rancher/k3s/server/db/state.db ]; then
    sqlite3 /var/lib/rancher/k3s/server/db/state.db \
      ".backup '$TMP/kubernetes/k3s-state.db.sqlite-backup'" 2>/dev/null || true
  fi
  kubectl get all -A > "$TMP/kubernetes/resources-all.txt" 2>/dev/null || true
fi
[ -d /etc/rancher/k3s ] && rsync -a --delete /etc/rancher/k3s/ "$TMP/kubernetes/etc-rancher-k3s/"
[ -d /var/lib/rancher/k3s/server/manifests ] && rsync -a --delete /var/lib/rancher/k3s/server/manifests/ "$TMP/kubernetes/manifests/"
[ -f /var/lib/rancher/k3s/server/token ] && install -m 600 /var/lib/rancher/k3s/server/token "$TMP/kubernetes/server-token"

# -----------------------------
# Docker volume metadata only
# The actual /var/lib/docker/volumes path is backed up by Borg directly.
# -----------------------------
if [ -d /var/lib/docker/volumes ]; then
  find /var/lib/docker/volumes -maxdepth 3 -mindepth 1 -print > "$TMP/docker/docker-volume-tree.txt" 2>/dev/null || true
fi

# -----------------------------
# Atomic publish of latest snapshot
# -----------------------------
rm -rf "${BASE}/previous"
if [ -d "$LATEST" ]; then
  mv "$LATEST" "${BASE}/previous"
fi

mv "$TMP" "$LATEST"
trap - EXIT
rm -rf "${BASE}/previous"

echo "App-data snapshot ready at ${LATEST}"
