# Script body below only used to create the script entity in the Borg UI that prepares app-consistent data for backup.
# The actual content of the script is in borg-prep-appdata-optiplex-two.sh, which is the one that gets executed by the Borg backup process.
# This script is essentially a placeholder that can be used to trigger the preparation of app-consistent data before the Borg backup runs,
# ensuring that all necessary information and data from the applications are captured in a consistent state for backup.
# Generated by borg-backup-survey.sh on 2026-07-03T11:55:00-04:00

# Name: optiplex-two-prep-appdata
# Description: Pre-backup app-data snapshot for optiplex-two services
# Run-on: Always - Regardless of result
# Time-out: 300 seconds (5 minutes)
# Script Content:

#!/bin/bash
set -Eeuo pipefail

echo "Starting optiplex-two pre-backup app-data prep..."

ssh \
  -o BatchMode=yes \
  -o StrictHostKeyChecking=accept-new \
  root@192.168.200.14 \
  /usr/local/sbin/borg-prep-appdata-optiplex-two.sh

echo "optiplex-two pre-backup app-data prep completed."
