#!/usr/bin/env bash

# This script prepares an app-consistent snapshot of relevant data for backup by Borg.
# Generated by borg-backup-survey.sh on 2026-10-05T01:39:26+00:00 for host: optiplex-three
# REVIEW BEFORE DEPLOYING - it reflects what was detected at survey time.
#
# It collects system information, Docker metadata, application data, database dumps,
# and platform state (Tailscale/Kubernetes where present). The resulting snapshot is
# staged in a temporary directory and atomically moved to the "latest" location for
# Borg to pick up. Run as root; backup data is protected with strict permissions (umask 077).
#
# Usage:
#   sudo ./borg-prep-appdata-optiplex-three.sh
# Deploy to /usr/local/sbin/borg-prep-appdata-optiplex-three.sh on optiplex-three and ensure Borg
# includes "${BASE}/latest" in its backup paths. Run before each Borg backup.
#
# Licensed under the MIT License. Provided "as is" without warranty.

set -Eeuo pipefail
umask 077

BASE="/var/backups/borg-apps"
LATEST="${BASE}/latest"

mkdir -p "$BASE"
TMP="$(mktemp -d "${BASE}/.tmp.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$TMP"/{metadata,docker,apps,databases,native,tailscale,kubernetes}

echo "Preparing app-consistent backup data for optiplex-three..."

# -----------------------------
# System and Docker inventory
# -----------------------------
{
  date -Is
  hostnamectl || true
  uname -a || true
  cat /etc/os-release || true
} > "$TMP/metadata/system-info.txt"

dpkg-query -W -f='${binary:Package}\t${Version}\n' > "$TMP/metadata/dpkg-packages.tsv" 2>/dev/null || true

docker ps -a --no-trunc > "$TMP/docker/docker-ps-a.txt" 2>/dev/null || true
docker images --digests > "$TMP/docker/docker-images.txt" 2>/dev/null || true
docker volume ls > "$TMP/docker/docker-volumes.txt" 2>/dev/null || true
docker network ls > "$TMP/docker/docker-networks.txt" 2>/dev/null || true

docker inspect $(docker ps -aq) > "$TMP/docker/docker-inspect-all.json" 2>/dev/null || true

# -----------------------------
# Home directory: /home/thomas
# -----------------------------
if [ -d /home/thomas ]; then
  rsync -a --delete \
    --exclude='*.db-wal' \
    --exclude='*.db-shm' \
    --exclude='.cache/' \
    /home/thomas/ "$TMP/apps/home-thomas/"
fi

# -----------------------------
# Kubernetes (k3s): datastore snapshot + config
# -----------------------------
if command -v k3s >/dev/null 2>&1; then
  # etcd datastore: use the built-in snapshot; SQLite datastore: safe-copy the db.
  if [ -d /var/lib/rancher/k3s/server/db/etcd ]; then
    k3s etcd-snapshot save --dir "$TMP/kubernetes/etcd-snapshots" >/dev/null 2>&1 \
      || echo "WARN: k3s etcd-snapshot failed"
  elif [ -f /var/lib/rancher/k3s/server/db/state.db ]; then
    sqlite3 /var/lib/rancher/k3s/server/db/state.db \
      ".backup '$TMP/kubernetes/k3s-state.db.sqlite-backup'" 2>/dev/null || true
  fi
  kubectl get all -A > "$TMP/kubernetes/resources-all.txt" 2>/dev/null || true
fi
[ -d /etc/rancher/k3s ] && rsync -a --delete /etc/rancher/k3s/ "$TMP/kubernetes/etc-rancher-k3s/"
[ -d /var/lib/rancher/k3s/server/manifests ] && rsync -a --delete /var/lib/rancher/k3s/server/manifests/ "$TMP/kubernetes/manifests/"
[ -f /var/lib/rancher/k3s/server/token ] && install -m 600 /var/lib/rancher/k3s/server/token "$TMP/kubernetes/server-token"

# -----------------------------
# Docker volume metadata only
# The actual /var/lib/docker/volumes path is backed up by Borg directly.
# -----------------------------
if [ -d /var/lib/docker/volumes ]; then
  find /var/lib/docker/volumes -maxdepth 3 -mindepth 1 -print > "$TMP/docker/docker-volume-tree.txt" 2>/dev/null || true
fi

# -----------------------------
# Atomic publish of latest snapshot
# -----------------------------
rm -rf "${BASE}/previous"
if [ -d "$LATEST" ]; then
  mv "$LATEST" "${BASE}/previous"
fi

mv "$TMP" "$LATEST"
trap - EXIT
rm -rf "${BASE}/previous"

echo "App-data snapshot ready at ${LATEST}"
