#!/usr/bin/env bash

# deploy-borg-prep-optiplex-three.sh
# Generated by borg-backup-survey.sh on 2026-10-06T14:30:55-04:00
#
# Installs a reviewed prep script to /usr/local/sbin on optiplex-three, keeping a backup of the
# version it replaces. Before installing it refuses files that are not a prep script (the
# BORG_UI SSH wrapper, CRLF line endings, syntax errors, wrong host) and shows a diff against
# what is installed now.
#
# Backups go to /mnt/backups/borg-script-backups/optiplex-three/<YYYYmmdd-HHMMSS>/ on the Synology
# share. If /mnt/backups is not mounted, nothing is installed or backed up.
#
# Usage (on optiplex-three):
#   sudo ./deploy-borg-prep-optiplex-three.sh [--yes] [--test] [SOURCE]
#                       SOURCE defaults to borg-prep-appdata-optiplex-three.sh next to this script
#   sudo ./deploy-borg-prep-optiplex-three.sh --rollback [--yes] [--test]
#                       reinstall the newest backup that differs from the installed script
#                       (the current version is backed up first)
#   sudo ./deploy-borg-prep-optiplex-three.sh --list
#   sudo ./deploy-borg-prep-optiplex-three.sh --backup-only
#                       back up the installed script without installing anything
#
#   --yes    install without the y/N prompt (required when not on a terminal)
#   --test   run the installed prep script afterwards
#
# Exit status: 0 success, 3 declined at the y/N prompt (nothing changed), other non-zero on error.
#
# Licensed under the MIT License. Provided "as is" without warranty.

set -Eeuo pipefail

NAME=optiplex-three
TARGET="/usr/local/sbin/borg-prep-appdata-${NAME}.sh"
BACKUP_MOUNT="/mnt/backups"
BACKUP_DIR="${BACKUP_MOUNT}/borg-script-backups/${NAME}"
KEEP_BACKUPS=10

ACTION="install" ASSUME_YES=0 RUN_TEST=0 SRC=""
while [ $# -gt 0 ]; do
  case "$1" in
    --rollback) ACTION="rollback"; shift ;;
    --list)     ACTION="list"; shift ;;
    --backup-only) ACTION="backup"; shift ;;
    --yes|-y)   ASSUME_YES=1; shift ;;
    --test)     RUN_TEST=1; shift ;;
    -h|--help)  awk 'NR>2 {if (!/^#/) exit; sub(/^# ?/,""); print}' "$0"; exit 0 ;;
    -*)         echo "Unknown option: $1" >&2; exit 1 ;;
    *)          SRC="$1"; shift ;;
  esac
done

die() { echo "ERROR: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run as root (sudo $0 ...)"

# Backup folders are named YYYYmmdd-HHMMSS, so a reverse name sort is newest first.
list_backups() { ls -1d "$BACKUP_DIR"/*/"borg-prep-appdata-${NAME}.sh" 2>/dev/null | sort -r || true; }

backup_mounted() {
  ls "$BACKUP_MOUNT/" >/dev/null 2>&1 || true   # wakes an x-systemd.automount
  mountpoint -q "$BACKUP_MOUNT"
}

require_backup_dir() {
  backup_mounted || die "$BACKUP_MOUNT is not mounted - mount the Synology backup share first. Nothing was changed."
  mkdir -p "$BACKUP_DIR" || die "cannot create $BACKUP_DIR - check the share's permissions. Nothing was changed."
}

backup_current() {
  local dir old tries=0
  require_backup_dir
  # mkdir without -p is atomic: if another backup already took this second, wait for the next one.
  dir="$BACKUP_DIR/$(date +%Y%m%d-%H%M%S)"
  until mkdir "$dir" 2>/dev/null; do
    [ -e "$dir" ] && [ "$tries" -lt 5 ] || die "cannot create $dir"
    tries=$((tries + 1))
    sleep 1
    dir="$BACKUP_DIR/$(date +%Y%m%d-%H%M%S)"
  done
  # NFS shares often squash root or use ACLs, so chmod/chown may be refused: keep both best-effort.
  chmod 700 "$dir" 2>/dev/null || true
  cp --preserve=timestamps "$TARGET" "$dir/borg-prep-appdata-${NAME}.sh"
  echo "Backed up current script to $dir/"
  list_backups | tail -n +$((KEEP_BACKUPS + 1)) | while read -r old; do
    [ "$old" = "$SRC" ] && continue   # never prune the backup a rollback is about to install
    rm -f "$old"
    rmdir "$(dirname "$old")" 2>/dev/null || true
  done
}

if [ "$ACTION" = "backup" ]; then
  [ -f "$TARGET" ] || die "nothing installed at $TARGET - nothing to back up"
  backup_current
  exit 0
fi

if [ "$ACTION" = "list" ]; then
  echo "Installed: $TARGET"
  [ -f "$TARGET" ] && ls -l "$TARGET"
  if backup_mounted; then
    echo "Backups in $BACKUP_DIR (newest first):"
    list_backups | sed 's/^/  /'
  else
    echo "Backups: $BACKUP_MOUNT is not mounted - cannot list them."
  fi
  exit 0
fi

if [ "$ACTION" = "rollback" ]; then
  require_backup_dir
  # Newest backup that differs from what is installed (after --backup-only the newest is identical).
  SRC=""
  while read -r b; do
    if [ ! -f "$TARGET" ] || ! cmp -s "$b" "$TARGET"; then SRC="$b"; break; fi
  done < <(list_backups)
  [ -n "$SRC" ] || die "no backup in $BACKUP_DIR differs from the installed script"
  echo "Rolling back to: $SRC"
else
  [ -n "$SRC" ] || SRC="$(dirname "$0")/borg-prep-appdata-${NAME}.sh"
fi

# -----------------------------
# Safety checks on the new file
# -----------------------------
[ -f "$SRC" ] && [ -s "$SRC" ] || die "source not found or empty: $SRC"

host="$(hostname -s)"
[ "$host" = "$NAME" ] || die "this host is '$host' but the script is for '$NAME' - deploy it on $NAME"

if [ "$(tr -cd '\r' < "$SRC" | wc -c)" -gt 0 ]; then
  die "$SRC has Windows (CRLF) line endings - fix with: sed -i 's/\r\$//' '$SRC'"
fi

if grep -q '^# Script Content:' "$SRC" \
   || { grep -qE '^[[:space:]]*ssh([[:space:]]|$)' "$SRC" && grep -qE '^[[:space:]]*root@' "$SRC"; }; then
  die "$SRC is the BORG_UI SSH wrapper, not the prep script. The wrapper belongs in the Borg UI script entity; installing it here makes the host SSH to itself."
fi

head -n1 "$SRC" | grep -q '^#!' || die "$SRC does not start with a #! line - is this the right file?"

grep -q 'borg-apps' "$SRC" || die "$SRC does not stage into /var/backups/borg-apps - is this a prep script?"

bash -n "$SRC" || die "syntax errors in $SRC"

# -----------------------------
# Show what changes
# -----------------------------
if [ -f "$TARGET" ] && cmp -s "$SRC" "$TARGET"; then
  echo "Installed script is already identical to $SRC - nothing to install."
else
  if [ -f "$TARGET" ]; then
    echo "Changes ($TARGET -> $SRC):"
    diff -u "$TARGET" "$SRC" || true
  else
    echo "No script installed yet at $TARGET (first install)."
  fi
  echo

  # No install without the backup share, checked before asking so a confirmed install never
  # fails at the backup step.
  require_backup_dir

  if [ "$ASSUME_YES" -ne 1 ]; then
    [ -t 0 ] || die "not on a terminal - re-run with --yes to install without prompting"
    printf 'Install %s to %s? [y/N] ' "$SRC" "$TARGET"
    read -r ans
    case "$ans" in y|Y|yes|YES) ;; *) echo "Aborted, nothing changed."; exit 3 ;; esac
  fi

  # -----------------------------
  # Back up current, install new
  # -----------------------------
  [ -f "$TARGET" ] && backup_current

  install -o root -g root -m 750 "$SRC" "$TARGET"
  echo "Installed $TARGET"
fi

if [ "$RUN_TEST" -eq 1 ]; then
  echo
  echo "Test run of $TARGET:"
  "$TARGET"
fi
